project:
  type: book
  output-dir: docs

execute:
  echo: false     
  warning: false   
  message: false
  
book:
  title: "Indicadores Brasileiros sobre Fiscalização Eletrônica de Velocidade"
  author:
  - name: Ana Beatriz da S. Marques
    orcid: 0009-0005-0639-8325
  - name: Jorge Tiago Bastos
    orcid: 0000-0001-6447-1504
  - name: Marcelo Corrêa de Paula Silva
  - name: Omar David Ordoñez Sayago
  date: 29/04/2026
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_diretrizes.qmd
    - 03_antecedentes.qmd 
    - 04_metodo.qmd
    - 05_resultados.qmd
    - 06_conclusoes.qmd
    - 99_references.qmd
  twitter-card: true
  repo-url: https://github.com/ONSV/rt_velocidade_2026
  cover-image: img/capa.png
  language: pt


bibliography: references.bib

editor: visual

format:
  html:
    theme: [cosmo, custom.scss]
    lang: pt
    fig-cap-location: top
    linkcolor: "#00496d"
    
    